apiVersion: v1
kind: Secret
metadata:
  name: hosts-secrets
  labels:
    app.kubernetes.io/component: hosts-secrets
    {{- include "apigateway.labels" . | nindent 4}}
type: Opaque
data:
  songs_host: {{ .Values.songsHost | b64enc }}
  support_host: {{ .Values.supportHost | b64enc }}
  messages_host: {{ .Values.messagesHost | b64enc }}
  users_host: {{ .Values.usersHost | b64enc }}