apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  labels:
    app.kubernetes.io/component: jwt-secrets
    {{- include "apigateway.labels" . | nindent 4}}
type: Opaque
data:
  jwt_secret: {{ .Values.jwtSecret | b64enc }}